let
    FromTable = (_table as table, keyColumns as list, nameColumn as text, dataColumn as text, itemKindColumn as text, itemNameColumn as text, isLeafColumn as text) as table =>
        let
            tableType = Value.Type(_table),
            newTableType = Type.AddTableKey(tableType, keyColumns, true) meta 
            [
                NavigationTable.NameColumn = nameColumn, 
                NavigationTable.DataColumn = dataColumn,
                NavigationTable.ItemKindColumn = itemKindColumn, 
                Preview.DelayColumn = itemNameColumn, 
                NavigationTable.IsLeafColumn = isLeafColumn
            ],
            navigationTable = Value.ReplaceType(_table, newTableType)
        in
            navigationTable,

    FromList = (rows as list, transform as function) as table =>
        let
            _list = List.Transform(rows, transform),
            _table = Table.FromRecords(_list)
        in
            FromTable(_table, {"Key"}, "Name", "Data", "ItemKind", "ItemName", "IsLeaf")
in
    [
        FromTable = FromTable,
        FromList = FromList
    ]